/**
 * src/lib/ecoBook.ts
 * 
 * Local offline opening book lookup.
 * Data sourced from the Lichess chess-openings project via hayatbiralem/eco.json.
 * Generated by: node scripts/download-eco.mjs
 * 
 * Usage:
 *   const opening = lookupOpening(fen);
 *   if (opening) {
 *     console.log(opening.name); // "Sicilian Defense: Dragon Variation"
 *     console.log(opening.eco);  // "B70"
 *   }
 */

// ecoBook.json is ~700KB (uncompressed). Next.js will tree-shake unused exports.
// This import is only bundled in the browser build (GamesPanel.tsx uses it).
// eslint-disable-next-line @typescript-eslint/no-require-imports
const ecoData = require("./ecoBook.json") as Record<string, { eco: string; name: string }>;

export interface OpeningInfo {
  eco: string;
  name: string;
}

/**
 * Look up opening theory by FEN.
 * Returns the opening ECO code and name, or null if the position is not in the book.
 * 
 * Note: FENs from chess.js include the move counters (e.g. "... 0 5").
 * The ECO database stores FENs with move counters, so matching is direct.
 */
export function lookupOpening(fen: string): OpeningInfo | null {
  return ecoData[fen] ?? null;
}

/**
 * Returns true if this position is in the ECO opening book.
 */
export function isBookPosition(fen: string): boolean {
  return fen in ecoData;
}
